- alias: Darkblue on
  trigger:
  - platform: state
    entity_id: input_boolean.swtheme
    from: 'off'
    to: 'on'
  action:
  - service: frontend.set_theme
    data:
      name: darkblue

- alias: Darkblue off
  trigger:
  - platform: state
    entity_id: input_boolean.swtheme
    from: 'on'
    to: 'off'
  action:
  - service: frontend.set_theme
    data:
      name: default