homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 144
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

shopping_list:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    ShoppingListAddItem:
      - Add {item} to my shopping list

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Text to speech
tts: !include_dir_list tts/

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret telegram_chat_id

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

weather:
   - platform: openweathermap
     name: openweather
     api_key: !secret openweathermap_api_key
     latitude: !secret home_latitude
     longitude: !secret home_longitude

script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml
media_player: !include media_player.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml