homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 144
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret


http: !include http.yaml
# Text to speech
tts: !include_dir_list tts/
script: !include scripts.yaml
group: !include groups.yaml
automation old: !include_dir_merge_named  automations_old/
automation: !include alarm.yaml
media_player: !include media_player.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
notify: !include notify.yaml
weather: !include weather.yaml


camera:
  - platform: local_file
    name: LogitechWeb
    file_path: /tmp/motion/lastsnap.jpg

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1234
    pending_time: 30
    armed_home:
      pending_time: 0
    triggered:
      pending_time: 20
    trigger_time: 4


shopping_list:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    ShoppingListAddItem:
      - Add {item} to my shopping list

logger:
  default: info
  logs:
    homeassistant.loader: error
    homeassistant.setup: error