- platform: template
  sensors:
    alarm1:
      friendly_name: "Время 1"
      value_template: >
        {{ states.input_slider.alarmhour1.state | int }}:
        {% if states.input_slider.alarmminutes1.state|length == 1 %}0{% endif %}
        {{ states.input_slider.alarmminutes1.state | int }}
    alarm2:
      friendly_name: "Время 2"
      value_template: '{{ states.input_slider.alarmhour2.state | int }}:{% if states.input_slider.alarmminutes2.state|length == 1 %}0{% endif %}{{ states.input_slider.alarmminutes2.state | int }}'

- platform: openweathermap
  api_key: !secret openweathermap_api_key
  language: ru
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - clouds
    - rain
    - snow
