- platform: template
  sensors:
    alarm1:
      friendly_name: 'Время1'
      value_template: '{{ states.input_number.alarmhour1.state | int }}:{{ states.input_number.alarmminutes1.state | int }}'

    alarm2:
      friendly_name: 'Время2'
      value_template: '{{ states.input_number.alarmhour2.state | int }}:{{ states.input_number.alarmminutes2.state | int }}'

- platform: openweathermap
  api_key: !secret openweathermap_api_key
  language: ru
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - clouds
    - rain
    - snow
